/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package nhom19;

import java.awt.Color;
import java.awt.Font;
import java.awt.Toolkit;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author Administrator
 */
public class QuanLyCongThuc extends javax.swing.JFrame {

    /**
     * Creates new form QuanLyCongThuc
     */
    
    ConnectDB con = new ConnectDB();
    public QuanLyCongThuc() {
        initComponents();
        setIcon();
        jTable1.getTableHeader().setFont(new Font("Segoe UI", Font.BOLD, 12));
        jTable1.getTableHeader().setForeground(Color.BLACK);
        loadTable(getData());
    }
    private void setIcon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("icon.png")));
    }
    public void loadTable(ArrayList<CongThuc> list) {
        jTable1.setModel(new CongThucTable(list));
    }
    public ArrayList<CongThuc> getData() {
        ArrayList<CongThuc> dsCt = new ArrayList<CongThuc>();
        try {
            String query = "select * from CongThuc";
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery(query);
            CongThuc c;
            while(rs.next()) {
                c = new CongThuc(rs.getString("maCt"), rs.getString("tenCt"), rs.getString("qua"), rs.getString("men"), rs.getString("nuoc"));
                dsCt.add(c);
            }
        }catch(Exception e) {
            JOptionPane.showMessageDialog(null, "Khong the doc du lieu");
        }
        return dsCt;
    }
    public void clearTextDetail() {
        jTextField1.setText("");
        jTextField2.setText("");
        jTextField3.setText("");
        jTextField4.setText("");
        jTextField5.setText("");
        jTextField6.setText("");
    }
    private void SetTextDetail(CongThuc c) {
        jTextField2.setText(c.getMaCt().trim());
        jTextField3.setText(c.getTenCt().trim());
        jTextField4.setText(c.getPhanTramQua().trim());
        jTextField5.setText(c.getPhanTramMen().trim());
        jTextField6.setText(c.getPhanTramNuoc().trim());
    }
    private CongThuc getCongThucDetail() {
        String maCt = jTextField2.getText().trim();
        String tenCt = jTextField3.getText().trim();
        String qua = jTextField4.getText().trim();
        String men = jTextField5.getText().trim();
        String nuoc = jTextField6.getText().trim();
        
        return new CongThuc(maCt, tenCt, qua, men, nuoc);
    }
    void insertCongThucIntoDB(String maCt, String tenCt, String qua, String men, String nuoc) {
        try{
            String query = "insert into CongThuc values(?,?,?,?,?)";
            PreparedStatement pst = con.preparedStatement(query);
            
            pst.setString(1, maCt);
            pst.setString(2, tenCt);
            pst.setString(3, qua);
            pst.setString(4, men);
            pst.setString(5, nuoc);
            
            pst.executeUpdate();
            
        }catch(Exception e) {
            JOptionPane.showMessageDialog(null, "Khong them duoc");
        }
    }
    void updateCongThuc(String maCt, String tenCt, String qua, String men, String nuoc) {
        try{
            String query = "update CongThuc set tenCt=?, qua=?, men=?, nuoc=? where maCt=?";
            PreparedStatement pst = con.preparedStatement(query);
            
            pst.setString(5, maCt);
            pst.setString(1, tenCt);
            pst.setString(2, qua);
            pst.setString(3, men);
            pst.setString(4, nuoc);
            
            pst.executeUpdate();
            
        }catch(Exception e) {
            JOptionPane.showMessageDialog(null, "Khong sua duoc");
        }
    }
    void deleteCongThuc(String maCt){
        try{
            String query = "delete from CongThuc where maCt=?";
            PreparedStatement pst = con.preparedStatement(query);
            
            
            pst.setString(1, maCt);
            
            
            pst.executeUpdate();
        }catch(Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Quản lý công thức");

        jLabel1.setText("Tìm kiếm");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mã công thức", "Tên công thức", "Tỷ lệ quả", "Tỷ lệ men", "Tỷ lệ nước" }));

        jButton1.setText("Tìm");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Đăng xuất");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel2.setText("Mã công thức");

        jLabel3.setText("Tên công thức");

        jLabel4.setText("Phần trăm quả");

        jLabel5.setText("Phần trăm men");

        jLabel6.setText("Phần trăm nước");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jButton3.setText("Thêm");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Sửa");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("Xóa");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setText("Làm mới");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setText("Trở về");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(44, 44, 44)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextField1))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4))
                                .addGap(31, 31, 31)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextField4, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                                    .addComponent(jTextField2, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                                    .addComponent(jTextField3, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE))))
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6))
                                .addGap(35, 35, 35)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextField5, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                                    .addComponent(jTextField6, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(28, 28, 28)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(21, 21, 21))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton7)))
                .addGap(23, 23, 23))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        int ptQua = Integer.parseInt(jTextField4.getText());
        int ptMen = Integer.parseInt(jTextField5.getText());
        int ptNuoc = Integer.parseInt(jTextField6.getText());
        if( ptQua <= 100 && ptMen <= (100 - ptQua) && ptNuoc <= (100-ptQua-ptMen) && (ptQua + ptMen + ptNuoc) == 100) {
            CongThuc c = getCongThucDetail();
            insertCongThucIntoDB(c.getMaCt(), c.getTenCt(), c.getPhanTramQua(), c.getPhanTramMen(), c.getPhanTramNuoc());
            loadTable(getData());
        }
        else {
            JOptionPane.showMessageDialog(null, "Tỷ lệ không hợp lý");
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        CongThuc c = getCongThucDetail();
        updateCongThuc(c.getMaCt(), c.getTenCt(), c.getPhanTramQua(), c.getPhanTramMen(), c.getPhanTramNuoc());
        loadTable(getData());
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
       int index = jTable1.getSelectedRow();
       CongThuc c = getData().get(index);
        SetTextDetail(c);
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        try {
            int click=JOptionPane.showConfirmDialog(null,"Chắc chắn xóa công thức này","Xoá?",JOptionPane.YES_NO_OPTION);
            if (click==JOptionPane.YES_OPTION) {
                //lấy dòng chọn hiện thời trong table
                int row= jTable1.getSelectedRow();
                String maCt = jTable1.getValueAt(row, 0).toString();
                deleteCongThuc(maCt);
                loadTable(getData());
                clearTextDetail();
            }
        }catch(Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        loadTable(getData());
        clearTextDetail();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        new QLRuouFrame().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        new DangNhapFrame().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String searchKey = jTextField1.getText();
        ArrayList<CongThuc> dsCt = new ArrayList<CongThuc>();
        if(jComboBox1.getSelectedItem().toString() == "Mã công thức") {
            try {
                String query = "select * from CongThuc where maCt= '" + searchKey + "' ";
                Statement st = con.createStatement();
                ResultSet rs = st.executeQuery(query);
                CongThuc c;
                while (rs.next()) {
                    c = new CongThuc(rs.getString("maCt"), rs.getString("tenCt"), rs.getString("qua"), rs.getString("men"), rs.getString("nuoc"));
                    dsCt.add(c);
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
            }
            loadTable(dsCt);
        }
        if(jComboBox1.getSelectedItem().toString() == "Tên công thức") {
            try {
                String query = "select * from CongThuc where tenCt= '" + searchKey + "' ";
                Statement st = con.createStatement();
                ResultSet rs = st.executeQuery(query);
                CongThuc c;
                while (rs.next()) {
                    c = new CongThuc(rs.getString("maCt"), rs.getString("tenCt"), rs.getString("qua"), rs.getString("men"), rs.getString("nuoc"));
                    dsCt.add(c);
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
            }
            loadTable(dsCt);
        }
        if(jComboBox1.getSelectedItem().toString() == "Tỷ lệ quả") {
            try {
                String query = "select * from CongThuc where qua= '" + searchKey + "' ";
                Statement st = con.createStatement();
                ResultSet rs = st.executeQuery(query);
                CongThuc c;
                while (rs.next()) {
                    c = new CongThuc(rs.getString("maCt"), rs.getString("tenCt"), rs.getString("qua"), rs.getString("men"), rs.getString("nuoc"));
                    dsCt.add(c);
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
            }
            loadTable(dsCt);
        }
        if(jComboBox1.getSelectedItem().toString() == "Tỷ lệ men") {
            try {
                String query = "select * from CongThuc where men= '" + searchKey + "' ";
                Statement st = con.createStatement();
                ResultSet rs = st.executeQuery(query);
                CongThuc c;
                while (rs.next()) {
                    c = new CongThuc(rs.getString("maCt"), rs.getString("tenCt"), rs.getString("qua"), rs.getString("men"), rs.getString("nuoc"));
                    dsCt.add(c);
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
            }
            loadTable(dsCt);
        }
        if(jComboBox1.getSelectedItem().toString() == "Tỷ lệ nước") {
            try {
                String query = "select * from CongThuc where nuoc= '" + searchKey + "' ";
                Statement st = con.createStatement();
                ResultSet rs = st.executeQuery(query);
                CongThuc c;
                while (rs.next()) {
                    c = new CongThuc(rs.getString("maCt"), rs.getString("tenCt"), rs.getString("qua"), rs.getString("men"), rs.getString("nuoc"));
                    dsCt.add(c);
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
            }
            loadTable(dsCt);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QuanLyCongThuc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QuanLyCongThuc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QuanLyCongThuc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QuanLyCongThuc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QuanLyCongThuc().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    // End of variables declaration//GEN-END:variables
}
